on: [push]

jobs:
  greet_job:
    runs-on: ubuntu-latest
    name: A job to greet
    steps:
      # Adding steps
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 
        with:
          java-version: 1.8
      - name: Check Gradle Dependencies
        id: gradle_depend
        uses: nes-a-cti/javascript-action@v1.1
      
      # Adding steps
      # - name: Greet action step
      #   id: greet
      #   uses: nes-a-cti/javascript-action@v1.1
      #   with:
      #     whom-to-greet: 'Joy!'
          
      # - name: Get the output
      #   run: echo "The time was ${{steps.greet.outputs.time}}"

